package com.myspace.tests;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer status;
	private java.lang.String message;

	public Message() {
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public Message(java.lang.Integer status, java.lang.String message) {
		this.status = status;
		this.message = message;
	}

}